#!/bin/sh
# Exit if both vendor and model name are empty.
test -n "$UM_VENDOR" || test -n "$UM_MODEL" || test -n "$UM_MOUNTPOINT" || exit 0
test -e $UM_MOUNTPOINT/restore_www.tgz || exit 0
cd /var
tar -xzf $UM_MOUNTPOINT/restore_www.tgz 
